const detail = {
    "_id": { "$oid": "667d9a5e246d464600bfac30" },
    "countryName": "India",
    "india":{
        "state": [
        { "name": "Andhra Pradesh", "id": 1, 
            "city":[
                { "name": "Kadapa" },
                { "name": "West Godavari", "localAreas": ["Bhimavaram"] },
                { "name": "Vizianagaram", "localAreas": ["Vizianagaram"] },
                { "name": "Visakhapatnam", "localAreas": ["Visakhapatnam"] },
                { "name": "Tirupati", "localAreas": ["Tirupati"] },
                { "name": "Srikakulam", "localAreas": ["Srikakulam"] },
                { "name": "Sri Sathya Sai", "localAreas": ["Puttaparthi"] },
                { "name": "Sri Potti Sriramulu Nellore", "localAreas": ["Nellore"] },
                { "name": "Prakasam", "localAreas": ["Ongole"] },
                { "name": "Parvathipuram Manyam", "localAreas": ["Parvathipuram"] },
                { "name": "Palnadu", "localAreas": ["Narasaraopeta"] },
                { "name": "Vijayawada", "localAreas": [] },
                { "name": "Nandyal", "localAreas": ["Nandyal"] },
                { "name": "Kurnool", "localAreas": ["Kurnool"] },
                { "name": "Krishna", "localAreas": ["Machilipatnam"] },
                { "name": "Konaseema", "localAreas": ["Amalapuram"] },
                { "name": "Kakinada", "localAreas": ["Kakinada"] },
                { "name": "Guntur", "localAreas": ["Guntur"] },
                { "name": "Eluru", "localAreas": ["Eluru"] },
                { "name": "East Godavari", "localAreas": ["Rajamahendravaram"] },
                { "name": "Chittoor", "localAreas": ["Chittoor"] },
                { "name": "Bapatla", "localAreas": ["Bapatla"] },
                { "name": "Annamayya", "localAreas": ["Rayachoti"] },
                { "name": "Anantapuramu", "localAreas": ["Anantapuram"] },
                { "name": "Anakapalli", "localAreas": ["Anakapalli"] },
                { "name": "Alluri Sitharama Raju", "localAreas": ["Paderu"] }
                ]},
        { "name": "Madhya Pradesh", "id": 2 },
        { "name": "Tripura", "id": 3 },
        { "name": "Arunachal Pradesh", "id": 4 },
        { "name": "Maharashtra", "id": 5 },
        { "name": "Uttar Pradesh", "id": 6 },
        { "name": "Assam", "id": 7 },
        { "name": "Manipur", "id": 8 },
        { "name": "Uttarakhand", "id": 9 },
        { "name": "Bihar", "id": 10 },
        { "name": "Meghalaya", "id": 11 },
        { "name": "West Bengal", "id": 12 },
        { "name": "Chhattisgarh", "id": 13 },
        { "name": "Mizoram", "id": 14 },
        { "name": "Andaman and Nicobar Islands", "id": 15 },
        { "name": "Goa", "id": 16 },
        { "name": "Nagaland", "id": 17 },
        { "name": "Chandigarh", "id": 18 },
        { "name": "Gujarat", "id": 19 },
        { "name": "Odisha", "id": 20 },
        { "name": "Dadra and Nagar Haveli and Daman and Diu", "id": 21 },
        { "name": "Haryana", "id": 22 },
        { "name": "Punjab", "id": 23 },
        { "name": "Jammu and Kashmir", "id": 24 },
        { "name": "Himachal Pradesh", "id": 25 },
        { "name": "Rajasthan", "id": 26 },
        { "name": "Ladakh", "id": 27 },
        { "name": "Jharkhand", "id": 28 },
        { "name": "Sikkim", "id": 29 },
        { "name": "Lakshadweep", "id": 30 },
        { "name": "Karnataka", "id": 31 },
        { "name": "Tamil Nadu", "id": 32 },
        { "name": "Delhi", "id": 33 },
        { "name": "Kerala", "id": 34 },
        { "name": "Telangana", "id": 35 },
        { "name": "Puducherry", "id": 36 }
        ],
    }

}

  